name: Onboarding request
description: Onboarding request for CIO customers
body:
  - type: checkboxes
    id: environment
    attributes:
      label: STAGE or PROD?
      options:
        - label: STAGE
        - label: PROD
  - type: checkboxes
    id: cluster
    attributes:
      label: Cluster Destination
      options:
        - label: stage-bdc-1
        - label: stage-lrk-1
  - type: input
    id: contact
    attributes:
      label: email
      description: Provide email address
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 3.x
        - 4.x
